import type { Channel } from './types';

// Mock channels for the demo / no-playlist-configured fallback.
// A curated US-market lineup — broadcast majors first, then sports,
// movies, news, kids, music, documentary. This is only shown when the
// user has no real M3U playlist; once they add a source, /api/m3u feeds
// their own channels in and these disappear.

function p(title: string, startMinAgo: number, durMin: number, desc?: string) {
  const start = new Date(Date.now() - startMinAgo * 60_000);
  const stop  = new Date(start.getTime() + durMin * 60_000);
  return { id: title.replace(/\s+/g, '-'), title, start, stop, description: desc, catchupAvailable: true };
}

export const MOCK_CHANNELS: Channel[] = [
  {
    id: 'nbc',
    number: 4,
    name: 'NBC',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/NBC_logo.svg/120px-NBC_logo.svg.png',
    category: 'Broadcast',
    now:   p('NBC Nightly News with Lester Holt', 14, 30, 'Top stories of the day, anchored from 30 Rockefeller Plaza.'),
    next1: p('Access Hollywood', -16, 30),
    next2: p('The Tonight Show Starring Jimmy Fallon', -46, 60),
  },
  {
    id: 'cbs',
    number: 2,
    name: 'CBS',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/CBS_logo.svg/120px-CBS_logo.svg.png',
    category: 'Broadcast',
    now:   p('CBS Evening News', 12, 30, 'The day\'s headlines from the CBS News bureau.'),
    next1: p('60 Minutes', -18, 60),
    next2: p('The Late Show with Stephen Colbert', -78, 60),
  },
  {
    id: 'abc',
    number: 7,
    name: 'ABC',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/American_Broadcasting_Company_Logo.svg/120px-American_Broadcasting_Company_Logo.svg.png',
    category: 'Broadcast',
    now:   p('World News Tonight with David Muir', 17, 30),
    next1: p('Jeopardy!', -13, 30),
    next2: p('Wheel of Fortune', -43, 30),
  },
  {
    id: 'fox',
    number: 5,
    name: 'FOX',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Fox_Broadcasting_Company_logo_%282019%29.svg/120px-Fox_Broadcasting_Company_logo_%282019%29.svg.png',
    category: 'Broadcast',
    now:   p('The Simpsons', 8, 30),
    next1: p('Family Guy', -22, 30),
    next2: p('Bob\'s Burgers', -52, 30),
  },
  {
    id: 'espn',
    number: 209,
    name: 'ESPN',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/120px-ESPN_wordmark.svg.png',
    category: 'Sports',
    now:   p('Monday Night Football: Chiefs vs Bills', 35, 195, 'Marquee primetime matchup — Patrick Mahomes vs Josh Allen.'),
    next1: p('SportsCenter', -160, 60),
    next2: p('NFL Live', -220, 60),
  },
  {
    id: 'espn2',
    number: 210,
    name: 'ESPN2',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/ESPN2_logo.svg/120px-ESPN2_logo.svg.png',
    category: 'Sports',
    now:   p('College GameDay', 20, 120),
    next1: p('NBA: Lakers vs Celtics', -100, 150),
    next2: p('First Take', -250, 90),
  },
  {
    id: 'fs1',
    number: 219,
    name: 'FS1',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Fox_Sports_1_logo.svg/120px-Fox_Sports_1_logo.svg.png',
    category: 'Sports',
    now:   p('UFC Fight Night Prelims', 25, 90),
    next1: p('UFC Fight Night Main Card', -65, 180),
    next2: p('Skip & Shannon: Undisputed', -245, 120),
  },
  {
    id: 'hbo',
    number: 301,
    name: 'HBO',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/120px-HBO_logo.svg.png',
    category: 'Movies',
    now:   p('Succession — Season Finale', 42, 75, 'The Roy family endgame. Limited commercial-free run.'),
    next1: p('The Last of Us', -33, 60),
    next2: p('Real Time with Bill Maher', -93, 60),
  },
  {
    id: 'showtime',
    number: 318,
    name: 'Showtime',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Showtime.svg/120px-Showtime.svg.png',
    category: 'Movies',
    now:   p('Yellowjackets', 18, 60),
    next1: p('Billions', -42, 60),
    next2: p('Top Gun: Maverick', -102, 130),
  },
  {
    id: 'amc',
    number: 322,
    name: 'AMC',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/AMC_logo_2016.svg/120px-AMC_logo_2016.svg.png',
    category: 'Movies',
    now:   p('The Walking Dead: Daryl Dixon', 22, 60),
    next1: p('Better Call Saul', -38, 60),
    next2: p('Mad Men — Marathon', -98, 240),
  },
  {
    id: 'cnn',
    number: 202,
    name: 'CNN',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/120px-CNN.svg.png',
    category: 'News',
    now:   p('Anderson Cooper 360°', 10, 60, 'Top of the hour with Anderson Cooper.'),
    next1: p('CNN Tonight', -50, 60),
    next2: p('The Lead with Jake Tapper', -110, 60),
  },
  {
    id: 'fox-news',
    number: 205,
    name: 'Fox News',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Fox_News_Channel_logo.svg/120px-Fox_News_Channel_logo.svg.png',
    category: 'News',
    now:   p('The Five', 5, 60),
    next1: p('Tucker Carlson Tonight', -55, 60),
    next2: p('Hannity', -115, 60),
  },
  {
    id: 'msnbc',
    number: 206,
    name: 'MSNBC',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/MSNBC_2015_logo.svg/120px-MSNBC_2015_logo.svg.png',
    category: 'News',
    now:   p('The Rachel Maddow Show', 0, 60),
    next1: p('All In with Chris Hayes', -60, 60),
    next2: p('The Last Word with Lawrence O\'Donnell', -120, 60),
  },
  {
    id: 'nick',
    number: 401,
    name: 'Nickelodeon',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Nickelodeon_2009_logo.svg/120px-Nickelodeon_2009_logo.svg.png',
    category: 'Kids',
    now:   p('SpongeBob SquarePants', 4, 30),
    next1: p('PAW Patrol', -26, 30),
    next2: p('Teenage Mutant Ninja Turtles', -56, 30),
  },
  {
    id: 'disney',
    number: 403,
    name: 'Disney Channel',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/2019_Disney_Channel_logo.svg/120px-2019_Disney_Channel_logo.svg.png',
    category: 'Kids',
    now:   p('Bluey', 7, 30),
    next1: p('Mickey Mouse Funhouse', -23, 30),
    next2: p('Frozen II', -53, 110),
  },
  {
    id: 'cartoon-network',
    number: 405,
    name: 'Cartoon Network',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/120px-Cartoon_Network_2010_logo.svg.png',
    category: 'Kids',
    now:   p('Teen Titans Go!', 11, 30),
    next1: p('We Bare Bears', -19, 30),
    next2: p('Adventure Time Marathon', -49, 120),
  },
  {
    id: 'mtv',
    number: 502,
    name: 'MTV',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/MTV_2021_%28brand_version%29.svg/120px-MTV_2021_%28brand_version%29.svg.png',
    category: 'Music',
    now:   p('Top 40 Countdown', 9, 60),
    next1: p('MTV Unplugged', -51, 60),
    next2: p('Ridiculousness', -111, 30),
  },
  {
    id: 'vh1',
    number: 504,
    name: 'VH1',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/VH1_logonew.svg/120px-VH1_logonew.svg.png',
    category: 'Music',
    now:   p('Behind the Music', 28, 60),
    next1: p('Love & Hip Hop: Atlanta', -32, 60),
    next2: p('Best Week Ever', -92, 30),
  },
  {
    id: 'nat-geo',
    number: 602,
    name: 'National Geographic',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Natgeologo.svg/120px-Natgeologo.svg.png',
    category: 'Documentary',
    now:   p('Drain the Oceans', 14, 60),
    next1: p('Cesar Millan: Better Human, Better Dog', -46, 60),
    next2: p('Free Solo', -106, 100),
  },
  {
    id: 'discovery',
    number: 604,
    name: 'Discovery',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Discovery_Channel_-_Logo_2019.svg/120px-Discovery_Channel_-_Logo_2019.svg.png',
    category: 'Documentary',
    now:   p('Gold Rush', 33, 60),
    next1: p('Deadliest Catch', -27, 60),
    next2: p('MythBusters Marathon', -87, 240),
  },
];
